### PR TITLE
Fix LUA_USE_DLOPEN definition

### PR DESCRIPTION
**Pull request by AntyMew**
Excuse me what

### CODE REVIEW

**Comment by viniciusjarina** [comment]
THis define is not needed, will be defined when you define USE_POSIX

**Comment by AntyMew** [comment]
Sorry for my tone, that was a rough day of troubleshooting

Looking back this PR was probably not the cleanest solution, but you are incorrect. USE_LINUX is the flag you are thinking of, and it defines USE_POSIX and USE_DLOPEN [here](https://github.com/NLua/lua/blob/eac8d04afd5028dced8e6863ff78155c5edacbb3/include/luaconf.h#L61). In fact the [original makefile](https://github.com/NLua/lua/blob/eac8d04afd5028dced8e6863ff78155c5edacbb3/src/Makefile#L105) accounts for this for multiple OSs. You can verify the issue with `nm liblua54.a | grep 'loadlib'`, or just by attempting to load a dynamic library

**Comment by sug44** [comment]
I had the same issue and was just going to open a pull request that is identical to this one. Basically exactly what @AntyMew said, LUA_USE_DLOPEN is never defined, but this bug only affects non windows systems. This means you can't require .so files and use `package.loadlib`. Can this be merged @viniciusjarina?

**Comment by viniciusjarina** [comment]
It should work. luaconf.h define it

**Comment by sug44** [comment]
@viniciusjarina [luaconf.h](https://github.com/NLua/lua/blob/eac8d04afd5028dced8e6863ff78155c5edacbb3/include/luaconf.h#L61) does define it but only if LUA_USE_LINUX or LUA_USE_MACOSX is defined.  For MacOS LUA_USE_MACOSX is getting defined in CMakeLists.txt, but LUA_USE_LINUX is not getting defined for Linux. I imagine you are using MacOS and thats why it works for you. This bug can also be fixed by defining LUA_USE_LINUX for linux if it doesn't cause any other issues

**Comment by viniciusjarina** [comment]
@sug44 you are right. I can't believe I oversight this for so many years.

**Pull request closed without merging**
